# This is a basic workflow to help you get started with Actions
# based on https://github.com/SteveSandersonMS/BlazorOnGitHubPages/blob/master/.github/workflows/main.yml 
name: CI
env:
  PUBLISH_DIR: nobodynuf.github.io/bin/Release/net7.0/publish/wwwroot/
  #PUBLISH_DIR: nobodynuf.github.io/bin/Release/netstandard2.1/publish/nobodynuf.github.io/dist
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Publish app
        run: dotnet publish -c Release

      - name: Make the CNAME file to allow my site to be visible in vanity url
        run: echo "page.nobodynuf.zip" > ${{ env.PUBLISH_DIR }}/CNAME
      - name: Make the discord file verification 
        run: mkdir .well-known && echo "dh=4943e2e36c3515d10e2d13b6be7f2e50549184a7" > ${{ env.PUBLISH_DIR }}/.well-known/discord
      #- name: Rewrite base href
      #  uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      #  with:
      #    html_path: ${{ env.PUBLISH_DIR }}/index.html
          # base_href: /nobodynuf.github.io/
      #    base_href: /
      - name: list the dir because i dont know how to debug stuff in CI
        run: dir ${{ env.PUBLISH_DIR }}
      
      - name: i dont know, make a .no-jekyll i guess
        run: cat > ${{ env.PUBLISH_DIR }}/.nojekyll

      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
          jekyll: False
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
